all:
	clear
	g++ main.cpp GUI.cpp GraphicElement.cpp ChessBoard.cpp ChessCase.cpp Point2I.cpp ClickableElement.cpp ChessPiece.cpp ChessPieceSet.cpp ChessGame.cpp -o GUI.out -lsfml-graphics -lsfml-window -lsfml-system


	
